name: Generate Pacman Game

on:
  schedule:
    - cron: "0 */12 * * *" # Berjalan otomatis setiap 12 jam
  workflow_dispatch:      # Mengizinkan tombol "Run workflow" manual
  push:
    branches:
      - main              # Berjalan otomatis jika Anda push ke branch main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          
      - name: Push pacman-contribution-graph.svg to the output branch
        env:
          GHP_KEY: ${{ secrets.GHP_KEY }}
        run: |
          cd dist
          git init
          git config user.name "${{ github.repository_owner }}"
          git config user.email "${{ github.repository_owner }}@users.noreply.github.com"
          git checkout -b output
          git add .
          git commit -m "chore: update pacman contribution graph [skip ci]"
          TOKEN="${GHP_KEY:-${{ secrets.GITHUB_TOKEN }}}"
          git push -f https://${{ github.repository_owner }}:${TOKEN}@github.com/${{ github.repository }}.git output